### ISSUE TITLE
1.8.23 在 Laravel 5.8 無法處理 AJAX 請求

### ISSUE THREAD

**Issue by jyhsu2000** [recca0120/laravel-tracy#50]
在 AJAX 請求回傳後
會緊接著一個送往 `/tracy/bar?_tracy_bar=content-ajax...` 的請求，用於取得要顯示在 bar 的內容
但在 Laravel 5.8 使用時
第二個請求不是送往 `/tracy/bar`，而是錯誤地送往當前頁面的路由

這會導致出現以下錯誤，而無法在 bar 顯示 AJAX 的請求
```
Uncaught SyntaxError: Unexpected token <
```

![image](https://user-images.githubusercontent.com/6276648/59156286-119ce580-8acb-11e9-9d62-ba81ede91bb7.png)

**Comment by danny50610** [comment]
如果設定 "tracy/tracy": "2.6.1" 就不會有這個問題了

**Comment by recca0120** [comment]
主要是 tracy/tracy 有做更新， composer update 就能解決

**Comment by jyhsu2000** [comment]
看到昨天這專案對`tracy/tracy`的版本要求有修改
於是又做了些嘗試
雖然不指定版本，讓它抓最新的`2.6.4`仍有相同狀況
但將`tracy/tracy`指定為`2.6.1`版確實就沒有此問題了
（後來嘗試發現`2.6.2`～`2.6.4`都還有這狀況）

**Comment by nemethit** [comment]
Interesting, I don't know why but this issue seems to appear form version to version again. But because I like the possibility to use Tracy also in productive-environments (for debug-reasons), I work with following function (simplified example without verification):

```
function isDebugRequest()
{
    $resultA = env('APP_DEBUG') === true;

    $resultB = isset($_GET['Debug']) && $_GET['Debug'] !== 'false'
        ? true
        : false;

    return isset($_GET['Debug']) ? $resultB : $resultA;
}
```

**Used in the config/Tracy.php like that**: 

```
return [
    'enabled' => ( isDebugRequest() ),
    'showBar' => ( isDebugRequest() ),
    ...
   ];
```

And use the property `Debug=false` in all AJAX request.
  
**Here an Easy example as GET-Request**:
`/customer/note/12345?Debug=false`

**Comment by fixcz** [comment]
I'm sorry but @nemeth-it's solution is not solution at all. It's not right to design your whole application around Tracy. Tracy should work on it's own when you need it no matter way the application is written.

I don't know the solution yet, but the issue still occurs with Tracy v2.8.10, Laravel-Tracy v1.16.0 and Laravel Framework v10.41.0.

This issue should stay open.
